server.port=8085
spring.application.name=history-service

# IBM DB2 Connection Properties
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:db2://db2:50000/histdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:db2inst1}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:db2pwd}
spring.datasource.driver-class-name=com.ibm.db2.jcc.DB2Driver

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.DB2Dialect
spring.jpa.show-sql=true
